apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - svc.yaml
  - deployment.yaml

configMapGenerator:
  - name: k8s-config
    namespace: test-gitops
    files:
      - my-config.ini

generatorOptions:
  disableNameSuffixHash: false

namespace: test-gitops
