apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-gitops-svc
  name: test-gitops-svc
spec:
  ports:
  - name: 8000-8000
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: test-gitops-deploy
  type: NodePort
